CREATE DATABASE TEST;

CREATE TABLE SEAN IN TEST;

CREATE TABLE SEAN(id INT,name STRING,amount INT);


CREATE TABLE SEAN(id UUID,name STRING, age INT, hobbies STRING[]);

INSERT VALUES ('1', '2','3') INTO TABLE SEAN;

FIND * IN SEAN;

FIND * IN SEAN
WHERE
	1 = 1;